# Generated by Django 4.0.2 on 2022-02-04 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captca', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuesModelQuesModel',
            new_name='QuesModel',
        ),
    ]
